version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "translate"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d1o81p1vgbak"
s3_prefix = "translate"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
